const Teste = require('./challenges.js');
console.log(Teste.compareTrue(1,2));
console.log(Teste.calcArea(1,4));
console.log(Teste.splitSentence("bianca caetano"));
console.log(Teste.concatName(["bianca", "de", "oliveira", "caetano"]));
console.log(Teste.footballPoints(3, 2));
console.log(Teste.highestCount([2, 5, 3, 4, 4, 4, 5, 6]));
console.log(Teste.catAndMouse(2, 5, 3));
Teste.fizzBuzz([2, 3, 4, 5, 10, 11]);
console.log(Teste.encode("hi there"));
console.log(Teste.decode("h3 th2r2"));
console.log(Teste.techList());
console.log(Teste.generatePhoneNumber([-3, 3, 3, 4, 5, 6, 7, 8, 9, 0, 1]));
